### Data Gathering and Model Training (model.ipynb)
	- select the kernel

- Load Data and import libraries

In [15]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error as mse, mean_absolute_error as mae, root_mean_squared_error as rmse

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/SagarChhabriya/data-science/refs/heads/main/datasets/TBD/salary_dataset.csv")
df

     Experience Years  Salary
0                 0.6   27868
1                 0.6   31381
2                 0.7   44204
3                 0.8   39551
4                 0.9   25984
..                ...     ...
195              14.6  158775
196              14.6  160741
197              14.6  170198
198              14.8  154396
199              14.8  173265

[200 rows x 2 columns]

- preprocessing + train test split

In [3]:
df.isna().sum()

Experience Years    0
Salary              0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [6]:
X = df['Experience Years']
y = df['Salary']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [13]:
X_train = X_train.values.reshape(-1,1)
X_test = X_test.values.reshape(-1,1)

- model training

In [14]:
lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

- Model evaluation

In [16]:
r2_score(y_pred, y_test)

0.9821864088840995

In [17]:
mse(y_pred, y_test)

23745684.25481864

In [18]:
mae(y_pred, y_test)

4056.3438613897365

In [19]:
rmse(y_pred, y_test)

4872.95436617445

Model Serialization

In [20]:
import pickle

with open("model.pkl", "wb") as file:
    pickle.dump(lr, file)

In [22]:
with open("model.pkl", "rb") as file:
   model = pickle.load(file)

In [23]:
df.head()

   Experience Years  Salary
0               0.6   27868
1               0.6   31381
2               0.7   44204
3               0.8   39551
4               0.9   25984

In [24]:
model.predict([[0.6]])

array([31417.94418739])